### ISSUE TITLE
Trailing Garbage

### ISSUE THREAD

**Issue by jonc92** [ewenme/understatr#5]
Hiya, 

Having a play with this package (it's great thanks). But have come across this error message: 

"Error: parse error: trailing garbage
          Chain":"0","xGBuildup":"0"}] [] [] []
                     (right here) ------^"

The code which triggers this is below:
# get EPL team data
epl_team_stats <- get_league_teams_stats(league_name = "EPL", year = 2018)
epl_team_stats

# get EPL player data
epl_player_stats <- purrr::map_dfr(unique(epl_team_stats$team_name), get_team_players_stats, year = 2018)
# determine the historical average delta_xG for EPL players

n <- epl_player_stats$player_id

xG_coeff_calc <- function(n)
{Player <- data.frame(get_player_seasons_stats(player_id = n))
Player$delta_xG <- Player$goals - Player$xG
Player <- subset(Player, select = c("xG", "goals", "delta_xG"))
mean(Player[,"delta_xG"])}

epl_player_stats$xG_coeff <- lapply(n, xG_coeff_calc)
  

I'm quite new to all of this but I think this problem originates from the code in the package? I'm not sure though... Do you know of a solution?

Thanks!

**Comment by ewenme** [comment]
thanks - I had a quick look and it's definitely a bug. The error occurs inside calls to `get_player_seasons_stats`, when called with certain `player_id`'s. It looks like players who have mostly all-zero season stats (e.g. [Jack Simpson](https://understat.com/player/6410)) are the problem. I will apply a fix shortly.

In future, I would advise including a [minimal reprex ](https://github.com/tidyverse/reprex)to demonstrate your problem. Makes it easier for me to recreate your problem and should generally get you favourable responses from developers!

**Comment by jonc92** [comment]
Hiya,

Hit a different bug here. 

```
# get EPL team data
epl_team_stats <- get_league_teams_stats(league_name = "EPL", year = 2018)

# get EPL player data
epl_player_stats <- purrr::map_dfr(unique(epl_team_stats$team_name), get_team_players_stats, year = 2018)
#> Error in str_subset(., "\\[\\]", negate = TRUE): unused argument (negate = TRUE)
```

Cheers!
