### ISSUE TITLE
Connection Timeout Issue

### ISSUE THREAD

**Issue by weerogue** [ewenme/understatr#6]
Getting connection timeout errors upon trying to run each command - any help appreciated!

> get_leagues_meta()
Error in open.connection(x, "rb") : 
  Timeout was reached: Connection timed out after 10000 milliseconds

**Comment by ewenme** [comment]
hey, I've been updating the package a bit today so try re-installing and re-running this...

In future, I would advise including a [minimal reprex](https://www.tidyverse.org/help/#reprex) to demonstrate your problem. Makes it easier for me to recreate your problem and should generally get you favourable responses from most developers!

**Comment by weerogue** [comment]
Thanks, appreciate this!
Will give it a try & bear that in mind.

Best, Jamie
