### ISSUE TITLE
Could not find function "get_data_element"

### ISSUE THREAD

**Issue by dotheway25** [ewenme/understatr#8]
> get_match_shots(match_id = 11662)
Error in get_data_element(match_data, "shotsData") : 
  **could not find function "get_data_element"**
In addition: Warning messages:
1: In if (wmc == TRUE & type != "score") { :
  the condition has length > 1 and only the first element will be used
2: In if (gf == TRUE & type != "score") { :
  the condition has length > 1 and only the first element will be used

I would have thought this function is a user-defined function within the package understatr, could you assist please?

**Comment by tonyelhabr** [comment]
I just tried this and it worked for me. Can you try re-installing and see if it works? (Yes, `get_data_element()` is a non-exported function in this package.)
